name: ecommerce_fe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  badges: ^3.1.2
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  google_fonts: ^6.0.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
